### ISSUE TITLE
Technical Issue

### ISSUE THREAD

**Issue by EmmaT07** [Josescherrer/WebTechProject#2]
Hi,

- You can use div to split the purpose and the founder part on the index page instead of using <br> so it will be easier for you to edit or style the sections when you need it.
- I think you can also use div for the alumni page so you can edit it with out changing other things in the future.

**Comment by Josescherrer** [comment]
Thank you for the feedback! For the index page I'm pretty sure I used div to divide the purpose and founder part but I'll look into using it for the alumni page.
